spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://auth-server:9000/oauth2/jwks

server.port=8080
spring.docker.compose.enabled=false

#Actuator
management.endpoint.health.probes.enabled=true
management.health.readinessstate.enabled=true
management.health.livenessstate.enabled=true

#Database
spring.data.mongodb.username=root
spring.data.mongodb.password=secret
spring.data.mongodb.database=admin
spring.data.mongodb.host=mongo
